### ISSUE TITLE
Disabling effect and adjusting parameters of another effect re-enables the first effect.

### ISSUE THREAD

**Issue by stylemistake** [photospice/photospice#1]
1. Turn off Vintage;
2. Move Hue on Olga-Bart;
3. Result: Vintage turns on silently.

If you adjust Vintage parameters again, it will turn off.

If you move Vintage to the bottom of the stack, it will quickly turn on/off while you move its parameter as browser events come in.

![image](https://user-images.githubusercontent.com/1516236/29179213-81b855da-7dfc-11e7-8f81-e1bfe9156caf.png)

**Comment by dcbrwn** [comment]
Nice catch!

Also there is related bug reported by @nerox8664 when disabling effect has same effect as you've described.

**Comment by dcbrwn** [comment]
Not fixed
